name: Atualização Semanal de Índices

on:
  schedule:
    - cron: '0 10 * * 4' # Toda quinta-feira às 07:00 AM (Brasília - UTC-3)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.jsrun
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Script
        run: node ./dist/run.js

      - name: Move indices.json to dist
        run: |
          if [ -f indices.json ]; then
            mv indices.json ./dist/
          fi

      - name: Commit Changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # Ou use secrets.GITHUB_TOKEN
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/${{ github.repository }}.git
          git add dist/indices.json          
          git commit -m "Atualização semanal de índices"
          git push
          git push origin main
