name: Atualização Semanal de Índices

on:
  schedule:
    - cron: '0 10 * * 4' # Toda quinta-feira às 07:00 AM (Brasília - UTC-3)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Compile TypeScript
        run: npx tsc

      - name: Run Script
        run: node ./dist/run.js

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dist/indices.json
          git commit -m "Atualização índices em $(date -d '-3 hours' '+%d/%m/%Y %H:%M')" || echo "Sem alterações"
          git push
